POST http://localhost:8080/course/add-course
Content-Type: application/json

{
  "course": "Clases de boxeo",
  "description": "Clases de boxeo para principiantes",
  "professor": "Rafael Carcamo Rosales",
  "schedule": "Lunes a Viernes 7:00 a 10:00"
}